# Generated by Django 5.1.5 on 2025-02-26 01:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('preciounitario', models.DecimalField(decimal_places=2, default=1.0, max_digits=9, verbose_name='Precio Unitario')),
                ('preciototal', models.DecimalField(decimal_places=2, default=1.0, max_digits=9, verbose_name='Precio Total')),
                ('descuento', models.DecimalField(decimal_places=2, default=1.0, max_digits=9, verbose_name='Descuento')),
                ('pagado', models.DecimalField(decimal_places=2, default=1.0, max_digits=9, verbose_name='Pagado')),
                ('estado', models.CharField(choices=[('S', 'Solicitado'), ('E', 'En proceso'), ('P', 'Pagado'), ('A', 'Autorizado'), ('N', 'No Autorizado'), ('C', 'Cancelado'), ('V', 'Vigente'), ('T', 'Tomado')], max_length=1, verbose_name='Estado')),
                ('fec_ini', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Inicio')),
                ('fec_fin', models.DateField(verbose_name='Fecha Termino')),
                ('comprobante', models.CharField(max_length=60, verbose_name='Comprobante')),
                ('foto_comp', models.CharField(max_length=200, verbose_name='Foto')),
                ('fec_reg', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('creo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.grupo')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
