# Generated by Django 5.1.5 on 2025-02-26 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='comprobante',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fec_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Termino'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fec_ini',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='foto_comp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Foto'),
        ),
    ]
