# Generated by Django 5.1.5 on 2025-02-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_inscripcion_comprobante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Pagado'),
        ),
    ]
