# Generated by Django 5.1.5 on 2025-03-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_inscripcion_descuento_alter_inscripcion_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('S', 'Solicitado'), ('E', 'En proceso'), ('P', 'Pagado'), ('A', 'Autorizado'), ('N', 'No Autorizado'), ('C', 'Cancelado'), ('V', 'Vigente'), ('T', 'Tomado')], default='S', max_length=1, verbose_name='Estado'),
        ),
    ]
