# Generated by Django 5.1.5 on 2025-06-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='fec_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fec_ini',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
