# Generated by Django 5.1.5 on 2025-07-17 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_grupo_fec_fin_grupo_fec_ini'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pagos_usados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Pagos Usados'),
        ),
        migrations.AddField(
            model_name='member',
            name='pagos_validado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Pagos Validados'),
        ),
        migrations.AddField(
            model_name='member',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Saldos '),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(max_length=80, verbose_name='Describe ')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Pagado')),
                ('RFC', models.CharField(max_length=15, verbose_name='RFC ')),
                ('documento', models.CharField(max_length=200, verbose_name='Documento ')),
                ('genero', models.CharField(choices=[('R', 'Registro'), ('N', 'Sin Validez'), ('V', 'Validado')], max_length=1, verbose_name='Género')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
