# Generated by Django 5.1.5 on 2025-07-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_pagos_usados_member_pagos_validado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='documento',
            field=models.FileField(upload_to='documentos_pagos/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='genero',
            field=models.CharField(choices=[('R', 'Registro'), ('N', 'Sin Validez'), ('V', 'Validado')], default='R', max_length=1, verbose_name='Estatus'),
        ),
    ]
