# Generated by Django 5.1.5 on 2025-07-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_pago_documento_alter_pago_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pagos_real',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Pagos Realizados'),
        ),
    ]
